openapi: 3.0.0
info:
  title: KidQuest API
  version: 1.0.0
  description: API documentation for KidQuest app

servers:
  - url: "http://localhost:8000"
    description: Local server

schemes: [http, https]

paths:
  /api/getAlphImg:
    get:
      summary: Get Alphabet Image
      responses:
        "200":
          description: Successfully retrieved alphabet image
        "500":
          description: Internal server error

  /api/getNumImg:
    get:
      summary: Get Number Image
      responses:
        "200":
          description: Successfully retrieved number image
        "500":
          description: Internal server error

  /api/getQuiz:
    get:
      summary: Get Quiz Data
      parameters:
        - name: category
          in: query
          required: true
          description: Quiz category (e.g., alphabet, number)
          schema:
            type: string
      responses:
        "200":
          description: Successfully retrieved quiz data
        "500":
          description: Internal server error

  /api/getUserQuiz:
    get:
      summary: Get User Quiz Data
      parameters:
        - name: category
          in: query
          required: true
          description: Quiz category (e.g., alphabet, number)
          schema:
            type: string
      responses:
        "200":
          description: Successfully retrieved user quiz data
        "500":
          description: Internal server error

  /api/login:
    post:
      summary: User Login
      requestBody:
        description: User login data
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                phone:
                  type: string
                  description: User's phone number
                password:
                  type: string
                  description: User's password
      responses:
        "200":
          description: Successfully logged in
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  token:
                    type: string
        "400":
          description: Bad request - Invalid input data
        "500":
          description: Internal server error

  /api/register:
    post:
      summary: User Registration
      requestBody:
        description: User registration data
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                formData:
                  type: object
                  properties:
                    name:
                      type: string
                      description: User's name
                    age:
                      type: string
                      description: User's age
                    phone:
                      type: string
                      description: User's phone number
                    password:
                      type: string
                      description: User's password
      responses:
        "200":
          description: Successfully registered
        "400":
          description: Bad request - Invalid input data
        "500":
          description: Internal server error

  /api/submitAnswer:
    post:
      summary: Submit User Answer
      requestBody:
        description: User answer data
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                answer:
                  type: string
                  description: User's answer
                qId:
                  type: string
                  description: Quiz ID
      parameters:
        - name: Authorization
          in: header
          required: true
          description: Bearer token for authentication
          schema:
            type: string
      responses:
        "200":
          description: Answer submitted successfully
        "400":
          description: Bad request - Invalid input data
        "401":
          description: Unauthorized - Invalid token
        "500":
          description: Internal server error

  /api/updateIndex:
    post:
      summary: Update User Quiz Index
      requestBody:
        description: User quiz index data
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                category:
                  type: string
                  description: Quiz category (e.g., alphabet, number)
                currentIndex:
                  type: number
                  description: Updated index value
      parameters:
        - name: Authorization
          in: header
          required: true
          description: Bearer token for authentication
          schema:
            type: string
      responses:
        "200":
          description: Index updated successfully
        "400":
          description: Bad request - Invalid input data
        "401":
          description: Unauthorized - Invalid token
        "500":
          description: Internal server error

  /api/user:
    get:
      summary: Get User Data
      parameters:
        - name: Authorization
          in: header
          required: true
          description: Bearer token for authentication
          schema:
            type: string
      responses:
        "200":
          description: Successfully retrieved user data
        "401":
          description: Unauthorized - Invalid token
        "500":
          description: Internal server error

  /api/reset:
    post:
      summary: Reset User Quiz Section
      requestBody:
        description: Reset data for a specific quiz section
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                category:
                  type: string
                  description: Quiz category (e.g., alphabet, number)
      parameters:
        - name: Authorization
          in: header
          required: true
          description: Bearer token for authentication
          schema:
            type: string
      responses:
        "200":
          description: Quiz section reset successfully
        "400":
          description: Bad request - Invalid input data
        "401":
          description: Unauthorized - Invalid token
        "500":
          description: Internal server error
