export const parentThoughts = [
  "Every child is unique, embrace and celebrate their individuality.",
  "Create a loving and supportive environment for your child to grow.",
  "Be present and actively listen when your child wants to share something.",
  "Encourage creativity and imagination; it's the foundation of learning.",
  "Teach the importance of kindness, empathy, and respect for others.",
  "Set reasonable expectations and celebrate both small and big achievements.",
  "Foster a love for learning by making it fun and engaging.",
  "Balance screen time with outdoor activities and real-world experiences.",
  "Lead by example; children often learn by observing their parents.",
  "Create a routine that provides stability and helps your child feel secure.",
  "Be patient and understanding, especially during challenging moments.",
  "Encourage healthy habits, including good nutrition and regular exercise.",
  "Teach the value of perseverance and learning from mistakes.",
  "Instill a strong sense of responsibility and accountability.",
  "Spend quality time together; it's the best investment in your relationship.",
  "Stay curious and explore the world with your child.",
  "Celebrate diversity and teach acceptance of different cultures and backgrounds.",
  "Support their passions and interests; it helps in personal growth.",
  "Stay positive and maintain a sense of humor; it makes parenting more enjoyable.",
  "Be open to communication about emotions, fears, and dreams.",
];
